"""titles table

Revision ID: 018e2946752a
Revises: a2ae4643a724
Create Date: 2020-07-24 13:11:15.263865

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '018e2946752a'
down_revision = 'a2ae4643a724'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('title',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(length=100), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_title_date_created'), 'title', ['date_created'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_title_date_created'), table_name='title')
    op.drop_table('title')
    # ### end Alembic commands ###
